name: org-struct

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      OSB_DATABASE_CONNECTION_STRING: postgresql+psycopg2://postgres:postgres@database:5432/postgres

  database:
    container_name: database
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  database-data:
