name: org-struct

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      OSB_DATABASE_CONNECTION_STRING: postgresql+psycopg2://postgres:postgres@database:5432/postgres

  database:
    image: postgres:17
    container_name: database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
